# Generated by Django 3.2.7 on 2022-07-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField()),
                ('campaign', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=55)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcard', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcard', to='products.category')),
                ('colors', models.ManyToManyField(related_name='productcard', to='products.Product')),
                ('show_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcard', to='products.color')),
                ('show_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcard', to='products.size')),
            ],
        ),
    ]
