# Generated by Django 3.2.7 on 2022-07-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('product_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
