# Generated by Django 3.2.7 on 2022-07-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_product', '0001_initial'),
        ('product_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='show_color',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='show_size',
        ),
        migrations.AddField(
            model_name='productcard',
            name='baseproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_product.baseproduct'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='base_product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product_cards.productcard')),
            ],
        ),
    ]
