# Generated by Django 3.2.7 on 2022-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('product_cards', '0002_productcard_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='products',
        ),
        migrations.AddField(
            model_name='productcard',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
