# Generated by Django 3.2.7 on 2022-07-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_product', '0001_initial'),
        ('products', '0002_auto_20220718_2303'),
        ('product_cards', '0002_auto_20220718_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='base_product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product_cards.productcard')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
