# Generated by Django 3.2.7 on 2022-07-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cards', '0003_auto_20220708_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='products',
        ),
    ]
