# Generated by Django 3.2.7 on 2022-07-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='link',
            new_name='url',
        ),
    ]
