name: tutor


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
    
      - uses: AutoModality/action-clean@v1      
      - uses: actions/checkout@v2
    
    
      - name: Stop trendyol-backend-v2_web_1 container
        run: | 
          docker stop trendyol-backend-v2_web_1 

      - name: Stop trendyol-backend-v2_db_1 container
        run: | 
          docker stop trendyol-backend-v2_db_1
          
      - name: Delete trendyol-backend-v2_web_1 container
        run: |
          docker rm trendyol-backend-v2_web_1 

          
      - name: Delete trendyol-backend-v2_db_1 container
        run: |
          docker rm trendyol-backend-v2_db_1
          
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
            
      - name: Makemigrations
        run: |
          docker-compose run web python3 manage.py makemigrations
          
      - name: Migrate
        run: |
          docker-compose run web python3 manage.py migrate
          
      - name: Collectstatic
        run: |
          docker-compose run web python3 manage.py collectstatic 
          
      - name: Createsuperuser
        run: |
          docker-compose run web python3 manage.py createsuperuser --noinput --username admin --email alatoo2022@gmail.com
